name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install systray dependencies
      run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
